version: "3"

services:
  mongo:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/var/lib/mongo

  app:
    restart: always
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DATABASE_DB=mongodb://localhost/express-starter-db

volumes:
  db-data:
